name: Pip2Conda

on: [push]

jobs:
  build:
    name: (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.7"]

    steps:

      - uses: actions/checkout@v2

      - name: Cache conda
        uses: actions/cache@v1
        env:
          # Increase this value to reset cache if requirements/conda_requirements.txt has not changed
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('requirements/conda_requirements.txt') }}

      - uses: goanpeca/setup-miniconda@v1
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          channels: defaults,conda-forge
          allow-softlinks: true
          channel-priority: flexible
          show-channel-urls: true
          use-only-tar-bz2: true

    - name: Install Dependencies
      run: |
        conda install --file requirements/conda_requirements.txt
        conda install --file requirements/test_requirements.txt
        conda install pyamg
        python setup.py install
        # sudo apt update --yes
        # sudo apt-get install mpich --yes
        # conda install mpi4py
        # conda install petsc petsc4py

      - name: Conda info
        shell: bash -l {0}
        run: conda info

      - name: Conda list
        shell: pwsh
        run: conda list
