name: Pip2Conda

on: [push]

jobs:
  build:

    name: (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.7"]

    steps:

      - uses: actions/checkout@v2

      - name: Cache conda
        uses: actions/cache@v1
        env:
          # + value -> force reset cache if requirements.txt hasn't changed
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('requirements/conda_requirements.txt') }}

      - uses: goanpeca/setup-miniconda@v1
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          channels: defaults,conda-forge
          allow-softlinks: true
          channel-priority: flexible
          show-channel-urls: true
          use-only-tar-bz2: true
          auto-activate-base: true

      - name: Install Dependencies
        shell: bash -l {0}
        run: |
          conda install --file requirements/conda_requirements.txt
          conda install --file requirements/test_requirements.txt
          sudo apt update --yes
          sudo apt-get install mpich --yes
          conda install pyamg mpi4py
          conda install petsc petsc4py
          python setup.py install

      # - name: Conda info
      #   shell: bash -l {0}
      #   run: conda info

      # - name: Conda list
      #   shell: pwsh
      #   run: conda list
