on: push
  # push:
  #   tags:
  #     - 'v*'

name: Create release notes

jobs:
  build:
    name: Release notes
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate release notes
        run: |
          echo ::set-env name=RELEASE_NOTES::$(./logger.sh)

      - name: Create release notes
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: env.RELEASE_NOTES
          draft: true
          prerelease: false
