name: Style Check

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0              # otherwise, you will failed to push refs to dest repo

      - name: Install style guide libs
        run:
          pip install flake8 wemake-python-styleguide

      - name: Get Diff Action
        uses: technote-space/get-diff-action@v4.0.1

      - name: Run style guide on changed files
        run:
          echo ${{ env.GIT_DIFF }}

      # For now, let's comment out the automated WPS style guide
      # - name: Find changed files
      #   run:
      #     echo "_CHANGED_FILES=$(git diff --name-only origin/${{ github.base_ref }} -- '*.py' | tr -s '\n' ' ' )" >> ${GITHUB_ENV}

      # - name: wemake-python-styleguide
      #   uses: wemake-services/wemake-python-styleguide@0.15.3
      #   with:
      #     reporter: 'github-pr-review'
      #     path: "${{ env._CHANGED_FILES }}"
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
